//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class approle
    {
        [Required]
        public int approleid { get; set; }

        [Required(ErrorMessage = "Role name is required.")]
        [Display(Name = "Role name ")]
        public string rolename { get; set; }
        public string note { get; set; }
    }
}
