//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactemail
    {
        public int contactemailid { get; set; }
        public Nullable<int> contactid { get; set; }
        public string emailaddress { get; set; }
    
        public virtual contact contact { get; set; }
    }
}
