//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class family
    {
        public family()
        {
            this.profiles = new HashSet<profile>();
        }
    
        [Required]
        public int familyid { get; set; }

        [Required(ErrorMessage="Family name is required.")]
        [Display(Name="Family name ")]
        public string familyname { get; set; }

        public string note { get; set; }
    
        public virtual ICollection<profile> profiles { get; set; }
    }
}
