//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class member
    {
        public member()
        {
            this.feerequests = new HashSet<feerequest>();
            this.signups = new HashSet<signup>();
            this.activities = new HashSet<activity>();
            this.member1 = new HashSet<member>();
            this.members = new HashSet<member>();
        }
    
        [Required]
        public int memberid { get; set; }
        [Required]
        [Display(Name="User name")]
        public string username { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current Password")]
        public string userpass { get; set; }

        [Required]
        [Display(Name="Password phrase")]
        public string passphrase { get; set; }
        public string memberstatus { get; set; }
        public Nullable<int> approleid { get; set; }
        public Nullable<int> studentid { get; set; }
        public Nullable<int> contactid { get; set; }
    
        public virtual approle approle { get; set; }
        public virtual contact contact { get; set; }
        public virtual ICollection<feerequest> feerequests { get; set; }
        public virtual student student { get; set; }
        public virtual ICollection<signup> signups { get; set; }
        public virtual ICollection<activity> activities { get; set; }
        public virtual ICollection<member> member1 { get; set; }
        public virtual ICollection<member> members { get; set; }
    }
}
