//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class member1
    {
        public member1()
        {
            this.feerequests = new HashSet<feerequest1>();
            this.signups = new HashSet<signup1>();
            this.activities = new HashSet<activity1>();
            this.contacts = new HashSet<contact1>();
            this.member11 = new HashSet<member1>();
            this.members = new HashSet<member1>();
            this.students = new HashSet<student1>();
        }
    
        public int memberid { get; set; }
        public string username { get; set; }
        public string userpass { get; set; }
        public string passphrase { get; set; }
        public string memberstatus { get; set; }
    
        public virtual ICollection<feerequest1> feerequests { get; set; }
        public virtual ICollection<signup1> signups { get; set; }
        public virtual ICollection<activity1> activities { get; set; }
        public virtual ICollection<contact1> contacts { get; set; }
        public virtual ICollection<member1> member11 { get; set; }
        public virtual ICollection<member1> members { get; set; }
        public virtual ICollection<student1> students { get; set; }
    }
}
