//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class sessiontype1
    {
        public sessiontype1()
        {
            this.sessioncals = new HashSet<sessioncal1>();
        }
    
        public int sessiontypeid { get; set; }
        public string typename { get; set; }
        public string note { get; set; }
    
        public virtual ICollection<sessioncal1> sessioncals { get; set; }
    }
}
