//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class signup
    {

        [Required]
        public int signupid { get; set; }

        [Required]
        public int memberid { get; set; }

        [Required]
        public int sessioncalid { get; set; }

        [Display(Name="Point earn ")]
        public Nullable<int> pointearn { get; set; }
        public string isshow { get; set; }
    
        public virtual member member { get; set; }
        public virtual sessioncal sessioncal { get; set; }
    }
}
