//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class student
    {
        public student()
        {
            this.profiles = new HashSet<profile>();
            this.profiles1 = new HashSet<profile>();
        }
    
        [Required]
        public int studentid { get; set; }

        [Required(ErrorMessage="First name is required.")]
        [Display(Name="First name ")]
        public string firstname { get; set; }

        [Required(ErrorMessage = "Last name is required.")]
        [Display(Name="Last name ")]
        public string lastname { get; set; }

        [Display(Name="Middle ")]
        public string middlename { get; set; }

        [Display(Name="Grade ")]
        public int grade { get; set; }

        [Display(Name="Active ")]
        public string active { get; set; }
    
        public virtual ICollection<profile> profiles { get; set; }
        public virtual ICollection<profile> profiles1 { get; set; }
    }
}
