//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class student1
    {
        public student1()
        {
            this.members = new HashSet<member1>();
        }
    
        public int studentid { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string middlename { get; set; }
        public Nullable<int> grade { get; set; }
        public string active { get; set; }
    
        public virtual ICollection<member1> members { get; set; }
    }
}
