//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public member()
        {
            this.feerequests = new HashSet<feerequest>();
            this.member2dependent = new HashSet<member2dependent>();
            this.signups = new HashSet<signup>();
            this.activities = new HashSet<activity>();
            this.contacts = new HashSet<contact>();
            this.students = new HashSet<student>();
        }
    
        public int memberid { get; set; }
        public string username { get; set; }
        public string userpass { get; set; }
        public string passphrase { get; set; }
        public string memberstatus { get; set; }
    
        public virtual ICollection<feerequest> feerequests { get; set; }
        public virtual ICollection<member2dependent> member2dependent { get; set; }
        public virtual ICollection<signup> signups { get; set; }
        public virtual ICollection<activity> activities { get; set; }
        public virtual ICollection<contact> contacts { get; set; }
        public virtual ICollection<student> students { get; set; }
    }
}
