//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PointAppDBEntities1 : DbContext
    {
        public PointAppDBEntities1()
            : base("name=PointAppDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<activity> activities { get; set; }
        public DbSet<contact> contacts { get; set; }
        public DbSet<contactemail> contactemails { get; set; }
        public DbSet<feerequest> feerequests { get; set; }
        public DbSet<member> members { get; set; }
        public DbSet<member2dependent> member2dependent { get; set; }
        public DbSet<sessioncal> sessioncals { get; set; }
        public DbSet<sessiontype> sessiontypes { get; set; }
        public DbSet<signup> signups { get; set; }
        public DbSet<student> students { get; set; }
    }
}
