//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class sessioncal
    {
        public int sessioncalid { get; set; }
        public System.DateTime sessiondate { get; set; }
        public int sessiontypeid { get; set; }
        public int sessionnum { get; set; }
        public Nullable<decimal> sessionamt { get; set; }
        public Nullable<int> sessionpoint { get; set; }
    
        public virtual sessiontype sessiontype { get; set; }
    }
}
