//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class family
    {
        public family()
        {
            this.profiles = new HashSet<profile>();
        }
    
        public int familyid { get; set; }
        public string familyname { get; set; }
        public string note { get; set; }
    
        public virtual ICollection<profile> profiles { get; set; }
    }
}
