//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public member()
        {
            this.contacts = new HashSet<contact>();
            this.feerequests = new HashSet<feerequest>();
            this.profiles = new HashSet<profile>();
            this.signups = new HashSet<signup>();
            this.activities = new HashSet<activity>();
        }
    
        public int memberid { get; set; }
        public string username { get; set; }
        public string userpass { get; set; }
        public string passsalt { get; set; }
        public Nullable<int> approleid { get; set; }
    
        public virtual ICollection<contact> contacts { get; set; }
        public virtual ICollection<feerequest> feerequests { get; set; }
        public virtual ICollection<profile> profiles { get; set; }
        public virtual ICollection<signup> signups { get; set; }
        public virtual ICollection<activity> activities { get; set; }
    }
}
