//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public contact()
        {
            this.contactemails = new HashSet<contactemail>();
            this.members = new HashSet<member>();
        }
    
        public int contactid { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string middlename { get; set; }
        public string address { get; set; }
        public string altaddress { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string homephone { get; set; }
        public string workphone { get; set; }
        public string mobilephone { get; set; }
    
        public virtual ICollection<contactemail> contactemails { get; set; }
        public virtual ICollection<member> members { get; set; }
    }
}
