//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class profile
    {
        [Required]
        public int profileid { get; set; }

        [Required]
        public int memberid { get; set; }

        [Required]
        [Display(Name="Status: ")]
        public string memberstatus { get; set; }

        public Nullable<int> studentid { get; set; }
        public Nullable<int> dependentid { get; set; }

        [Required]
        [Display(Name="Family name: ")]
        public string familyname { get; set; }
    
        public virtual member member { get; set; }
        public virtual student student { get; set; }
        public virtual student student1 { get; set; }
    }
}
